### ISSUE TITLE
IndexOutOfBoundsException in AuditLogValidator

### ISSUE THREAD

**Issue by vladgusev** [GoogleCloudPlatform/bigquery-data-lineage#28]
Getting IndexOutOfBoundsException when running pipeline.

Error message from worker: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        java.base/java.util.Objects.checkIndex(Objects.java:372)
        java.base/java.util.ArrayList.get(ArrayList.java:458)
        com.google.cloud.solutions.datalineage.transform.AuditLogValidator$MessageValidator.validDestinationTable(AuditLogValidator.java:66)
        com.google.cloud.solutions.datalineage.transform.AuditLogValidator$MessageValidator.isProcessableEvent(AuditLogValidator.java:56)
        com.google.cloud.solutions.datalineage.transform.AuditLogValidator.apply(AuditLogValidator.java:38)
        com.google.cloud.solutions.datalineage.transform.AuditLogValidator.apply(AuditLogValidator.java:31)
        org.apache.beam.sdk.transforms.Filter$1.processElement(Filter.java:210)
 

Offending code (.get(0) below) from AuditLogValidator.java

  ```
  private boolean validDestinationTable() {
      BigQueryTableEntity destinationTable =
          fromBigQueryResource(
              parser.forSubNode(METADATA_ROOT).<List<String>>read(QUERY_DESTINATION_TABLE).get(0));
```

**Comment by anantdamle** [comment]
Hi @vladgusev,
thanks for logging the issue.
Can I request you to kindly share a sample BigQuery Audit log for me to reproduce the issue.

**Comment by anantdamle** [comment]
This issue arises when the BigQuery operation is a DML or DDL statement. Closing this issue
